### ISSUE TITLE
USER STORY: Manage studio posts

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/ceramics-studio-platform#15]
As a **Site Admin**, I can **create, read, update and delete posts** so that ** I can manage the Social Ceramics platform**.

## Acceptance criteria: 

- **Acceptance criteria one:** Site admin can add a new post from the admin panel.
- **Acceptance criteria two:** Site admin can save as a draft or publish the post from the admin panel.
- **Acceptance criteria three:** Site admin can edit the post from the admin panel.
- **Acceptance criteria four:** Site admin can delete the post from the admin panel.

## Tasks

- [x] Task 1: Create superuser
- [x] Task 2: Create "Postview" model 
- [x] Task 3: Create view
- [x] Task 4: Create "index" template
- [x] Task 5: Test functionality
- [ ]
