### ISSUE TITLE
USER STORY: Learn about the teachers at the studio

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/ceramics-studio-platform#16]
As a **Site User**, I can **find out who the teachers at the studio are** so that **I can become more familiar with the studio and know who posted**.

## Acceptance criteria: 

- **Acceptance criteria one:** There should be a photo of each teacher.
- **Acceptance criteria two:** The should be a brief introduction to each teacher.
- **Acceptance criteria three:**

## Tasks

- [ ] Task 1: Create "about" model 
- [ ] Task 2: Create view
- [ ] Task 3: Create "about" template
- [ ] Task 4: Test functionality
