### ISSUE TITLE
USER STORY: Register as User

### ISSUE THREAD

**Issue by YasmineBB** [YasmineBB/ceramics-studio-platform#2]
As a **Site User**, I can **register an account** so that **I can book classes and share my work and like and comment on other students work on the platform**.

## Acceptance Criteria

- Acceptance Criteria 1: Site user can register with their username and password.
- Acceptance Criteria 2: Site user is notified when they have registered and are able to login in with the details they have entered.
- Acceptance Criteria 3: 

## Tasks

- [ ] Task 1: Create register button in navigation bar.
- [ ] Task 2: Set up all auth registration.
- [ ] Task 3:Set up custom form to add first and last name.
